### ISSUE TITLE
插件默认配置文件生成错误

### ISSUE THREAD

**Issue by 3328429240** [0XPYEX0/FlyWithFood#10]
[18:05:35] [Server thread/INFO]: [FlyWithFood] Enabling FlyWithFood v1.4.1
[18:05:35] [Server thread/INFO]: [FlyWithFood]  
[18:05:35] [Server thread/INFO]: [FlyWithFood] 感谢使用FlyWithFood.
[18:05:35] [Server thread/INFO]: [FlyWithFood] 本项目在GitHub开源: https://github.com/0XPYEX0/FlyWithFood
[18:05:35] [Server thread/INFO]: [FlyWithFood] 本项目在Gitee开源: https://gitee.com/xpyex/FlyWithFood
[18:05:35] [Server thread/INFO]: [FlyWithFood]  
[18:05:35] [Server thread/INFO]: [FlyWithFood] Thank you for using FlyWithFood
[18:05:35] [Server thread/INFO]: [FlyWithFood] The plugin has been open source in GitHub: https://github.com/0XPYEX0/FlyWithFood
[18:05:35] [Server thread/INFO]: [FlyWithFood] Have a nice trip with this plugin  :)
[18:05:35] [Server thread/INFO]: [FlyWithFood]  
[18:05:35] [Server thread/INFO]: [FlyWithFood] 已与Vault挂钩
[18:05:35] [Server thread/INFO]: [FlyWithFood] 配置文件丢失？正在生成配置文件!
[18:05:35] [Server thread/INFO]: [FlyWithFood] Lost your configuration file? The configuration file is being generated for you!
[18:05:35] [Server thread/INFO]: [FlyWithFood]  
[18:05:35] [Server thread/ERROR]: Error occurred while enabling FlyWithFood v1.4.1 (Is it up to date?)
java.lang.NoSuchMethodError: com/google/gson/JsonArray.add(Ljava/lang/String;)V (loaded from file:/F:/danji/MineCraft/cache/patched_1.8.8.jar by sun.misc.Launcher$AppClassLoader@480141f) called from class me.xpyex.plugin.flywithfood.common.config.ConfigUtil (loaded from file:/F:/danji/MineCraft/plugins/FlyWithFood.jar by org.bukkit.plugin.java.PluginClassLoader@b961ddc1).
	at me.xpyex.plugin.flywithfood.common.config.ConfigUtil.getNewConfig(ConfigUtil.java:52) ~[?:?]
	at me.xpyex.plugin.flywithfood.bukkit.config.HandleConfig.getNewConfig(HandleConfig.java:233) ~[?:?]
	at me.xpyex.plugin.flywithfood.bukkit.config.HandleConfig.createConfigFile(HandleConfig.java:128) ~[?:?]
	at me.xpyex.plugin.flywithfood.bukkit.config.HandleConfig.loadConfig(HandleConfig.java:49) ~[?:?]
	at me.xpyex.plugin.flywithfood.bukkit.FlyWithFood.onEnable(FlyWithFood.java:60) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135) [%5B插件锁定%5DPerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
[18:05:35] [Server thread/INFO]: [FlyWithFood] Disabling FlyWithFood v1.4.1

**Comment by 0XPYEX0** [comment]
或是Gson版本过老导致，等待修复

**Comment by 0XPYEX0** [comment]
#11
