### ISSUE TITLE
插件报错刷屏

### ISSUE THREAD

**Issue by 3328429240** [0XPYEX0/FlyWithFood#11]
[08:22:40 WARN]: Exception in thread "Craft Scheduler Thread - 1038(这个数字一直在变)" 
[08:22:40 WARN]: org.apache.commons.lang.UnhandledException: Plugin FlyWithFood v1.4.2 generated an exception while executing task 285
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:823)
>Caused by: java.lang.NoSuchMethodError: com/google/gson/JsonArray.contains(Lcom/google/gson/JsonElement;)Z (loaded from file:/F:ji/MineCraft/Dream_Space7/cache/patched_1.8.8.jar by sun.misc.Launcher$AppClassLoader@37529918) called from class me.xpyex.plugin.flywithfood.bukkit.implementations.BukkitUser (loaded from file:/F:ji/MineCraft//Dream_Space7ugins/%5B饥饿飞行%5DFlyWithFood.jar by org.bukkit.plugin.java.PluginClassLoader@cac5a7c1).
at me.xpyex.plugin.flywithfood.bukkit.implementations.BukkitUser.inNoFunction(BukkitUser.java:100)
at me.xpyex.plugin.flywithfood.bukkit.implementations.BukkitUser.needCheck(BukkitUser.java:105)
at me.xpyex.plugin.flywithfood.bukkit.FlyWithFood.lambda$startCheck$1(FlyWithFood.java:127)
at me.xpyex.plugin.flywithfood.bukkit.FlyWithFood$$Lambda$990/0x0000000000000000.run(Unknown Source)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by 0XPYEX0** [comment]
Gson版本过旧导致，无法修复

**Comment by 0XPYEX0** [comment]
#10
