### ISSUE TITLE
无法解析服务端版本

### ISSUE THREAD

**Issue by blackshou** [0XPYEX0/FlyWithFood#14]
```
[02:41:12 INFO]: [FlyWithFood] Enabling FlyWithFood v2.0.3*
[02:41:12 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.getVersion()
[02:41:12 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[02:41:12 WARN]:        at FlyWithFood-2.0.3-all.jar//me.xpyex.plugin.flywithfood.bukkit.api.FlyWithFoodAPIBK.<clinit>(FlyWithFoodAPIBK.java:41)
[02:41:12 WARN]:        at FlyWithFood-2.0.3-all.jar//me.xpyex.plugin.flywithfood.bukkit.FlyWithFoodBukkit.onEnable(FlyWithFoodBukkit.java:21)
[02:41:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:41:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[02:41:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[02:41:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611)
[02:41:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525)
[02:41:12 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[02:41:12 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[02:41:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:343)
[02:41:12 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1116)
[02:41:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[02:41:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:41:12 INFO]: [INFO] [FlyWithFood]  
[02:41:12 INFO]: [ERROR] [FlyWithFood] 无法自动解析服务端版本，使用默认版本信息
[02:41:12 INFO]: [ERROR] [FlyWithFood] Failed to get Server Version... Using default version info
```

**Comment by 0XPYEX0** [comment]
请使用Bug反馈模板~
