### ISSUE TITLE
[Feature] 可以更新到1.20甚至1.21吗虽然现在也可以用，但有报错

### ISSUE THREAD

**Issue by niubikelashi** [0XPYEX0/FlyWithFood#15]
```
[FlyWithFood] Enabling FlyWithFood v2.0.3*
[13:50:32 警告]: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.getVersion()
[13:50:32 警告]:        at java.base/java.lang.Class.getMethod(Class.java:2395)
[13:50:32 警告]:        at FlyWithFood-2.0.3-all.jar//me.xpyex.plugin.flywithfood.bukkit.api.FlyWithFoodAPIBK.<clinit>(FlyWithFoodAPIBK.java:41)
[13:50:32 警告]:        at FlyWithFood-2.0.3-all.jar//me.xpyex.plugin.flywithfood.bukkit.FlyWithFoodBukkit.onEnable(FlyWithFoodBukkit.java:21)
[13:50:32 警告]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[13:50:32 警告]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[13:50:32 警告]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:50:32 警告]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:50:32 警告]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:644)
[13:50:32 警告]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:555)
[13:50:32 警告]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669)
[13:50:32 警告]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[13:50:32 警告]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[13:50:32 警告]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1130)
[13:50:32 警告]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314)
[13:50:32 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:50:32 信息]: [信息] [FlyWithFood]  
[13:50:32 信息]: [错误] [FlyWithFood] 无法自动解析服务端版本，使用默认版本信息
[13:50:32 信息]: [错误] [FlyWithFood] Failed to get Server Version... Using default version info
[13:50:32 信息]: [信息] [FlyWithFood] 你使用的服务端核心: Unknown-Leaves-1.20.4-R0.1-SNAPSHOT
[13:50:32 信息]: [信息] [FlyWithFood] You are using the server software: Unknown-Leaves-1.20.4-R0.1-SNAPSHOT
```

**Comment by 0XPYEX0** [comment]
这个不是啥问题，只是Bukkit改方法了，获取不到版本信息而已
功能都是正常的，这个错误可以忽视

**Comment by niubikelashi** [comment]
确实，功能都是正常的，确实可以忽略，但对强迫症不友好哈哈哈

**Comment by 0XPYEX0** [comment]
#14
