### ISSUE TITLE
[Bug] 适配1.21

### ISSUE THREAD

**Issue by Cnzw** [0XPYEX0/FlyWithFood#16]
**描述**
请求适配1.21

**截图**
```
[00:30:20] [Server thread/ERROR]: Error occurred while enabling FlyWithFood v2.0.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[purpur-1.21.jar:1.21-2280-930003b]
	at FlyWithFood-2.0.6-all.jar/me.xpyex.plugin.flywithfood.bukkit.FlyWithFoodBukkit.onEnable(FlyWithFoodBukkit.java:38) ~[FlyWithFood-2.0.6-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2280-930003b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "21-R0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:661) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:777) ~[?:?]
	at FlyWithFood-2.0.6-all.jar/me.xpyex.plugin.flywithfood.bukkit.api.FlyWithFoodAPIBK.<clinit>(FlyWithFoodAPIBK.java:50) ~[FlyWithFood-2.0.6-all.jar:?]
	... 18 more
[00:30:20] [Server thread/INFO]: [FlyWithFood] Disabling FlyWithFood v2.0.6
[00:30:20] [Server thread/ERROR]: Error occurred while disabling FlyWithFood v2.0.6
java.lang.IllegalStateException: 插件尚未加载完成 || Plugin is invalid
	at FlyWithFood-2.0.6-all.jar/me.xpyex.plugin.flywithfood.common.FlyWithFood.getInstance(FlyWithFood.java:19) ~[FlyWithFood-2.0.6-all.jar:?]
	at FlyWithFood-2.0.6-all.jar/me.xpyex.plugin.flywithfood.common.FlyWithFood.disable(FlyWithFood.java:30) ~[FlyWithFood-2.0.6-all.jar:?]
	at FlyWithFood-2.0.6-all.jar/me.xpyex.plugin.flywithfood.bukkit.FlyWithFoodBukkit.onDisable(FlyWithFoodBukkit.java:27) ~[FlyWithFood-2.0.6-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2280-930003b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.jar:1.21-2280-930003b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**版本信息(请参照例子，不要胡编乱造):**

- 操作系统: Windows
- Minecraft 1.21
- 服务端核心 Current Purpur Version: 1.21-2280-930003b (MC: 1.21)*
- FlyWithFood 2.0.6

**Comment by 0XPYEX0** [comment]
这个Bug我在另一个项目修过，这个项目没人反馈我都忘了()
是解析版本的时候出现错误了，FWF会尝试去获取游戏的主版本
例如1.20.4，获取到的结果是20
1.21后面没有版本号，所以解析出错了
换言之如果1.21.1来用插件就不会报错()
